modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="minecracked"
version="1.0.0"
displayName="minecracked"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Rainb, MCreator"

[[dependencies.minecracked]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




